### PR TITLE
A little bigger fix.

### PR DESCRIPTION
**Pull request by Albin323**
### Pull Request Description

Fixed sv.json. Where a few problems in the translation. Added Qbox and qb to utils. Added Qbox.lua

## Major Changes
fix: Fixed Swedish Translation
feat: Added Qbox and Qb to utils.lus
refactor: Added Qbox.lua in frameworks
## Modifications done
- [x] 🍃 New Feature
- [x] ♻️ Refactor
- [x] 🐛 Bug Fix
- [x] 🎨 Design
- [ ] 🔥 Optimization
- [ ] 🎒 Other

### CODE REVIEW

**Comment by Albin323** [comment]
image
Picture to show he simcard.png

**Comment by Maximus7474** [comment]
I asked previously to follow the contributing guidelines.
- [Commit Messages](https://github.com/Maximus7474/lb-phone-simcards/blob/main/CONTRIBUTING.md#commit-messages)

**Comment by Albin323** [comment]
If this isn't right i have no idéa what i need to do.

**Comment by Maximus7474** [comment]
When contributing to a public repository you need to follow the contributing guidelines if applicable.
commit-conventions

**Pull request closed without merging**
